// src/renderer/components/shared/Dropdown.tsx
import React, {
  MouseEventHandler,
  PropsWithChildren,
  useEffect,
  useState,
} from "react";
import { classList } from "../../../shared/dom";

export interface DropdownProps {
  active?: boolean;
  trigger: JSX.Element;
  onSelect?: (ev: React.MouseEvent<HTMLElement>) => any;
}

export function Dropdown(props: PropsWithChildren<DropdownProps>) {
  const [active, setActive] = useState(props.active ?? false);
  const classes = classList("dropdown", { "is-active": active });

  const toggle = (ev: any) => {
    ev.stopPropagation();
    setActive(!active);
  };

  const close = () => {
    setActive(false);
  };

  // Listen for prop changes when an external trigger is being used.
  useEffect(() => {
    window.addEventListener("click", close);
    setActive(props.active ?? false);

    return () => {
      window.removeEventListener("click", close);
    };
  }, [props.active]);

  const onItemClick = (ev: React.MouseEvent<HTMLElement>) => {
    ev.stopPropagation();
    setActive(false);

    props.onSelect?.(ev);
  };

  return (
    <div className={classes}>
      <div className="dropdown-trigger" onClick={toggle}>
        {props.trigger}
      </div>
      <div className="dropdown-menu">
        <div className="dropdown-content" onClick={onItemClick}>
          {props.children}
        </div>
      </div>
    </div>
  );
}

// src/components/core/Dropdown.vue
<template>
    <div :class="`dropdown ${isActive ? 'is-active' : ''}`">
        <div class="dropdown-trigger">
            <slot name="trigger" :toggle="toggle"> </slot>
        </div>

        <slot name="menu">
            <div class="dropdown-menu">
                <div class="dropdown-content">
                    <slot name="content"> </slot>
                </div>
            </div>
        </slot>
    </div>
</template>

<script lang="ts">
import { climbDomHierarchy } from '@/utils/dom/climb-dom-hierarchy';
import { defineComponent, onBeforeUnmount, onMounted, ref } from 'vue';

export default defineComponent({
    props: {
        active: {
            type: Boolean,
            default: false
        }
    },
    setup(p) {
        const isActive = ref(p.active);
        const toggle = (e: Event) => {
            e.stopPropagation();

            const newValue = !isActive.value;

            if (newValue) {
                window.addEventListener('click', listenForBlur);
            } else {
                window.removeEventListener('click', listenForBlur);
            }

            isActive.value = newValue;
        };

        const listenForBlur = (e: MouseEvent) => {
            const isWithinMenu = climbDomHierarchy<boolean>(e.target as HTMLElement, {
                match: (el) => el.classList.contains('dropdown-menu')
            });

            // User clicked outside of dropdown menu. Hide it.
            if (!isWithinMenu) {
                isActive.value = false;
            }
        };

        return {
            isActive,
            toggle
        };
    }
});
</script>
